language: node_js
node_js: '10'
install:
- npm install
script:
- npm test
notification:
  slack:
    rooms:
      secure: hBydsQ/nPi0YbXS1f+3nQFhGlGj9b6hiC1gc4pwVSfEH2w/7Y/UZusdDszN4KsFAEV8t9TAcQq855j4p8XqamgNKJpoU97q7eJjQxNRqdgsg48Yx2sWnQHixKaO++zRrBNakPRMggAVOh46Knmg59Y6RaILJIjiI17m1jI5TBBvtvz+NBou8mgDznyLRENyl3xA5YQRrPOvSqGhCeZsuUsGRWxs5hKPB33+Jnid8D/kjuL8lCySLcxAiknIIn70MvZQPVYAmf7C4giwZz22F27Q5GYF9SxTyX4Sc+jzK6KiqjWkpRzJIVNNmLSeFaEQmthLr51/GsJkwH6UlkpdTsmfw70vQkFE/g+djYZ8kf1Xp5SBECkTMLyjOhuSWJQi7uh23NZKavavht4Q+Yi7fe97L9opslq3UDHDMZWOW977/0jd2849/3pVI86KXhY/fiGhjsSBfFBT5uuCJem27IuJ1OJiwKxpZ05NYd8TDmqmUo2GsXFIr6EuQ120DYo4L/kVeHPyFWKE1xSS91V5h9ehzqZLvRvvQD3xqkS6gFVa2LyyIGFKoSPmEGDuLd4OyC9MX/wUR+s9hMQWXqO5ReoMLpXFY5Um0LmwoBfrgY88rfw5U7UiumnTKMn6xNb503VHGR+ZxFeyETBmLzMEpnpgPiQ8PYIjRo+XHYqBbAHg=
